sudo: required
services:
  - docker

before_install:
  - docker build -t jorgesorianoalva/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jorgesorianoalva/docker-react npm run test